name: Build & Push Docker Image

on:
  workflow_dispatch:  # Manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gh-action-test2:21f3002611 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gh-action-test2:21f3002611
